name: RumbaController

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cargo_clippy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2021-01-07
        components: clippy, rustfmt, rust-src
    - name: Run cargo fmt check
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
        toolchain: nightly-2021-01-07
    - name: Run cargo clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
        toolchain: nightly-2021-01-07

  cargo_check:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2021-01-07
        components: rust-src
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
        toolchain: nightly-2021-01-07
